version: "5.2.0"
services:
  app:
    build: .
    container_name: vite-react-express
    command: npm run dev
    image: vite-react-express:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/app
